### ISSUE TITLE
Could not load PEM file on Ubuntu 22.04

### ISSUE THREAD

**Issue by Firionus** [rustls/rustls-native-certs#48]
`load_native_certs` returns an Err with "Could not load PEM file" on my PC. 

## Steps to Reproduce

```
git clone https://github.com/rustls/rustls-native-certs.git
cd rustls-native-certs
git checkout v/0.6.2
cargo test
```
Result:
```
    Finished test [unoptimized + debuginfo] target(s) in 0.03s
     Running unittests src/lib.rs (target/debug/deps/rustls_native_certs-f7d973d62fa334c9)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/compare_mozilla.rs (target/debug/deps/compare_mozilla-534257af1aea96a0)

running 3 tests
test test_does_not_have_many_roots_unknown_by_mozilla ... FAILED
test test_contains_most_roots_known_by_mozilla ... FAILED
test util_list_certs ... FAILED

failures:

---- test_does_not_have_many_roots_unknown_by_mozilla stdout ----
thread 'test_does_not_have_many_roots_unknown_by_mozilla' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidData, error: "Could not load PEM file \"/usr/lib/ssl/certs/ca-certificates.crt\"" }', tests/compare_mozilla.rs:69:59

---- test_contains_most_roots_known_by_mozilla stdout ----
thread 'test_contains_most_roots_known_by_mozilla' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidData, error: "Could not load PEM file \"/usr/lib/ssl/certs/ca-certificates.crt\"" }', tests/compare_mozilla.rs:107:59
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- util_list_certs stdout ----
thread 'util_list_certs' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidData, error: "Could not load PEM file \"/usr/lib/ssl/certs/ca-certificates.crt\"" }', tests/compare_mozilla.rs:147:59


failures:
    test_contains_most_roots_known_by_mozilla
    test_does_not_have_many_roots_unknown_by_mozilla
    util_list_certs

test result: FAILED. 0 passed; 3 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s

error: test failed, to rerun pass '--test compare_mozilla'
```

Full Backtrace: https://gist.github.com/Firionus/7eefc8e8844bef2c9749b09813465b23#file-full-backtrace-terminal-dump

## Expected Behavior

`load_native_certs` should return an Ok instead of Err. 

## Infos

```
$ cargo --version --verbose
cargo 1.62.1 (a748cf5a3 2022-06-08)
release: 1.62.1
commit-hash: a748cf5a3e666bc2dcdf54f37adef8ef22196452
commit-date: 2022-06-08
host: x86_64-unknown-linux-gnu
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:OpenSSL/1.1.1n)
os: Ubuntu 22.04 (jammy) [64-bit]
```

`/usr/lib/ssl/certs/ca-certificates.crt` exists and looks like this: https://gist.github.com/Firionus/7eefc8e8844bef2c9749b09813465b23#file-ca-certificates-crt

A restart had no effect. Updating the system packages via apt had no effect. `update-ca-certificates` was run multiple times with and without the --fresh option, it never made a difference. 

## Related Issues

This problem appeared downstream in https://github.com/JuliaLang/juliaup/issues/335.

**Comment by djc** [comment]
Would you happen to have `SSL_CERT_FILE` set? Please try with this PR: https://github.com/rustls/rustls-native-certs/pull/49.

**Comment by Firionus** [comment]
> Would you happen to have `SSL_CERT_FILE` set? 

Nope: 
```
$ printenv SSL_CERT_FILE
$ 
```

> Please try with this PR: #49.

```
$ git log -1
commit 5b9af69a8e2409b744cae3f164d10de294762511 (HEAD -> orig-error, origin/orig-error)
Author: Dirkjan Ochtman <dirkjan@ochtman.nl>
Date:   Mon Jul 25 12:02:01 2022 +0200

    Bump MSRV to 1.52

$ cargo test
    Finished test [unoptimized + debuginfo] target(s) in 0.03s
     Running unittests src/lib.rs (target/debug/deps/rustls_native_certs-4652a560630fe29b)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/compare_mozilla.rs (target/debug/deps/compare_mozilla-dc90f2a6082cf15c)

running 3 tests
test test_does_not_have_many_roots_unknown_by_mozilla ... FAILED
test test_contains_most_roots_known_by_mozilla ... FAILED
test util_list_certs ... FAILED

failures:

---- test_does_not_have_many_roots_unknown_by_mozilla stdout ----
thread 'test_does_not_have_many_roots_unknown_by_mozilla' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidData, error: "Could not load PEM file \"/usr/lib/ssl/certs/ca-certificates.crt\": stream did not contain valid UTF-8" }', tests/compare_mozilla.rs:69:59
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- test_contains_most_roots_known_by_mozilla stdout ----
thread 'test_contains_most_roots_known_by_mozilla' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidData, error: "Could not load PEM file \"/usr/lib/ssl/certs/ca-certificates.crt\": stream did not contain valid UTF-8" }', tests/compare_mozilla.rs:107:59

---- util_list_certs stdout ----
thread 'util_list_certs' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidData, error: "Could not load PEM file \"/usr/lib/ssl/certs/ca-certificates.crt\": stream did not contain valid UTF-8" }', tests/compare_mozilla.rs:147:59


failures:
    test_contains_most_roots_known_by_mozilla
    test_does_not_have_many_roots_unknown_by_mozilla
    util_list_certs

test result: FAILED. 0 passed; 3 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s

error: test failed, to rerun pass '--test compare_mozilla'

```

**Comment by djc** [comment]
Okay, well, you have a bunch of garbage in your ca-certificates.crt:

https://gist.github.com/Firionus/7eefc8e8844bef2c9749b09813465b23#file-ca-certificates-crt-L2519

**Comment by Firionus** [comment]
Indeed, `ca-certificates.crt` is not valid UTF-8:

```
$ isutf8 ca-certificates.crt 
ca-certificates.crt: line 2519, char 2, byte 153259: Expecting bytes in the following ranges: 00..7F C2..F4.
```

Here's the original file, the byte code was mangled when I pasted it to Gist: [ca-certificates.zip](https://github.com/rustls/rustls-native-certs/files/9180892/ca-certificates.zip)

**Comment by djc** [comment]
The mangling doesn't matter. The reason this fails is because your `ca-certificates.crt` contains garbage (that is, data that doesn't look like PEM-encoded certificates). I don't know how that got there, but given that you're the first person to report this, I'm pretty sure it's someone about your environment that's crapped over your CA store. Maybe you should check which package repository the file came from, but this is not a rustls-native-certs bug.

**Comment by Firionus** [comment]
Unfortunately I also have no idea how that mangled part got there. I can't recall doing anything to my certificates on purpose ever. 

However, I'd vote to reopen. To my understanding the PEM file format is defined in [RFC 7468](https://datatracker.ietf.org/doc/html/rfc7468). The mangled part is outside the encapsulation boundaries and about that [Section 2](https://datatracker.ietf.org/doc/html/rfc7468#section-2) says:

> Data before the encapsulation boundaries are permitted, and parsers MUST NOT malfunction when processing such data.

The fact that curl works fine with the file (https://github.com/JuliaLang/juliaup/issues/335#issuecomment-1190608982) and openssl also eats it just fine would resemble that requirement:

```
/etc/ssl/certs$ openssl storeutl -noout -certs ca-certificates.crt 
0: Certificate
1: Certificate
2: Certificate
[output shortened]
126: Certificate
Total found: 127
```

So shouldn't this crate be able to handle that garbage?

**Comment by djc** [comment]
I've submitted a fix here: https://github.com/rustls/pemfile/pull/7.
